#!/bin/sh
#SBATCH -e err
#SBATCH -o out
#SBATCH --account=nosofs
#SBATCH --qos=batch
#SBATCH --partition=hercules
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=80
#SBATCH --time=07:00:00
#SBATCH --job-name="run_schism"
##SBATCH --exclusive
set -eux
echo -n " $(date +%s)," > job_timestamp.txt
set +x
echo $PWD
module purge
module load intel-oneapi-compilers/2023.2.4
module load intel-oneapi-mpi/2021.13.0
module load hdf5/1.14.3
module load netcdf-fortran/4.6.1
module load libjpeg-turbo/2.1.3
export NETCDF_C_ROOT=/apps/spack-managed/oneapi-2023.2.4/netcdf-c-4.9.2-qgy4pbuiliwyxhppgqgyb2jtc2vgfhzf
export NETCDF_FORTRAN_ROOT=/apps/spack-managed/oneapi-2023.2.4/netcdf-fortran-4.6.1-6agxmmk6cbyavt472y6ds2d3b5ppekni
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NETCDF_C_ROOT/lib:$NETCDF_FORTRAN_ROOT/lib:/apps/other/pyferret-7.6.0/lib
ulimit -s unlimited
echo "Model started:  " $(date)
# Number of scribes
NUM_SCRIBES=9
# SCHISM executable
SCHISM_EXEC=./pschism_HERCULES_BLD_STANDALONE_TVD-VL
# Run SCHISM with srun
srun --label -n $SLURM_NTASKS $SCHISM_EXEC $NUM_SCRIBES
echo "Model ended:    " $(date)
